### ISSUE TITLE
NPE if chat is reloaded a few times

### ISSUE THREAD

**Issue by axay** [smilefam/SendBird-Android#2]
`E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                               Process: com.bedbathmore, PID: 3437
                                                               java.lang.NullPointerException
                                                                   at com.sendbird.android.SendBird$SendBirdClient$45.onOpen(SendBird.java:2540)
                                                                   at com.sendbird.android.WSClient$4.onOpen(WSClient.java:237)
                                                                   at com.sendbird.android.shadow.okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:149)
                                                                   at com.sendbird.android.shadow.okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
                                                                   at com.sendbird.android.shadow.okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
                                                                   at com.sendbird.android.shadow.okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
                                                                   at com.sendbird.android.shadow.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                   at java.lang.Thread.run(Thread.java:841)`

**Comment by sf-jay-yun** [comment]
Please try the latest SDK.
Not only v3, SDK v2 might as well have been stabilized.
