### ISSUE TITLE
Error inflating class ImageView

### ISSUE THREAD

**Issue by divya21raj** [smilefam/SendBird-Android#38]
Error on Mi 4W on Android 6.0.1:

android.view.InflateException: Binary XML file line #63: Binary XML file line #8: Error inflating class ImageView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at com.data.collector.wifigues.SendBird.groupchannel.GroupChannelListAdapter.onCreateViewHolder(GroupChannelListAdapter.java:167)
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6519)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5706)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
        at android.view.View.layout(View.java:16669)
        at android.view.ViewGroup.layout(ViewGroup.java:5440)
        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:611)
        at android.view.View.layout(View.java:16669)
        at android.view.ViewGroup.layout(ViewGroup.java:5440)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16669)
        at android.view.ViewGroup.layout(ViewGroup.java:5440)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16669)
        at android.view.ViewGroup.layout(ViewGroup.java:5440)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
        at android.view.View.layout(View.java:16669)
        at android.view.ViewGroup.layout(ViewGroup.java:5440)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16669)
        at android.view.ViewGroup.layout(ViewGroup.java:5440)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16669)
        at android.view.ViewGroup.layout(ViewGroup.java:5440)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16669)
        at android.view.ViewGroup.layout(ViewGroup.java:5440)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
        at android.view.View.layout(View.java:16669)
        at android.view.ViewGroup.layout(ViewGroup.java:5440)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
        at android.view.View.layout(View.java:16669)
        at android.view.ViewGroup.layout(ViewGroup.java:5440)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2207)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1963)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6064)

-Happens in GroupChannelListAdapter.onCreateViewHolder when trying to inflate list_item_group_channel.xml, which is like this....

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="86.5dp"
    android:background="?attr/selectableItemBackground"
    android:clickable="true"
    android:paddingLeft="14dp"
    android:paddingRight="14dp">

    <com.stfalcon.multiimageview.MultiImageView
        android:id="@+id/image_group_channel_list_cover"
        android:layout_width="56dp"
        android:layout_height="56dp"
        android:layout_centerVertical="true"
        android:scaleType="centerCrop" />

    <LinearLayout
        android:id="@+id/container_group_channel_list_topic"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignTop="@id/image_group_channel_list_cover"
        android:layout_marginLeft="16dp"
        android:layout_toRightOf="@id/image_group_channel_list_cover"
        android:gravity="center_vertical"
        android:orientation="horizontal">

        <TextView
            android:id="@+id/text_group_channel_list_topic"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:ellipsize="end"
            android:maxLines="1"
            android:maxWidth="160dp"
            android:text="Anna Bluiasdfasdfasdfasdfasdfasdfasdfasdfafm"
            android:textColor="#000000"
            android:textSize="16sp" />

        <TextView
            android:id="@+id/text_group_channel_list_member_count"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginLeft="8dp"
            android:layout_marginStart="8dp"
            android:gravity="center"
            android:maxLines="1"
            android:minWidth="16dp"
            android:paddingLeft="4dp"
            android:paddingRight="4dp"
            android:text="3"
            android:textSize="12sp" />

    </LinearLayout>

    <LinearLayout
        android:id="@+id/container_group_channel_list_message"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignLeft="@id/container_group_channel_list_topic"
        android:layout_below="@id/container_group_channel_list_topic"
        android:orientation="horizontal">

        <include
            android:id="@+id/container_group_channel_list_typing_indicator"
            layout="@layout/layout_typing_indicator"
            android:layout_width="32dp"
            android:layout_height="16dp"
            android:layout_marginTop="4dp" />

        <TextView
            android:id="@+id/text_group_channel_list_message"
            android:layout_width="223dp"
            android:layout_height="32dp"
            android:layout_marginTop="2dp"
            android:ellipsize="end"
            android:maxLines="2"
            android:text="This sounded nonsense to Alice, so she said nothing, but set off at her being blah blah"
            android:textColor="#8e8e8e"
            android:textSize="14sp" />

    </LinearLayout>

    <TextView
        android:id="@+id/text_group_channel_list_date"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true"
        android:layout_alignTop="@id/container_group_channel_list_topic"
        android:layout_marginTop="3dp"
        android:maxLines="1"
        android:text="9999/99/99"
        android:textSize="11.5sp" />

    <TextView
        android:id="@+id/text_group_channel_list_unread_count"
        android:layout_width="24dp"
        android:layout_height="24dp"
        android:layout_alignParentBottom="true"
        android:layout_alignParentEnd="true"
        android:layout_alignParentRight="true"
        android:layout_marginBottom="16dp"
        android:background="@drawable/group_chat_admin_background"
        android:gravity="center"
        android:maxLines="1"
        android:text="9+"
        android:textColor="@color/white" />
</RelativeLayout>

**Comment by divya21raj** [comment]
Some drawables were not in correct places, solved now..
