### ISSUE TITLE
NPE while connecting to sendbird

### ISSUE THREAD

**Issue by anirudha-banerjee** [smilefam/SendBird-Android#7]
I'm using the recent version i.e v3.0.10
This happens sometimes, not all the time.

`E/UncaughtException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.sendbird.android.User.getUserId()' on a null object reference
                                                                             at com.sendbird.android.SendBird$3$2.run(SendBird.java:306)
                                                                             at android.os.Handler.handleCallback(Handler.java:815)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                             at android.os.Looper.loop(Looper.java:194)
                                                                             at com.sendbird.android.SendBird$3$1.run(SendBird.java:291)`

**Comment by sf-jay-yun** [comment]
Can you check the version again?
Because, there no part to call getUserId() on SendBird.java:306

Maybe you can be using earlier version.

**Comment by anirudha-banerjee** [comment]
I am using the latest version i.e 3.0.10
This issue is happening in a Lenovo Tab with android 5, not in any mobile device. But that's alright cause my app is targeted towards mobile devices.
Thanks for replying.

**Comment by sf-jay-yun** [comment]
The issue you are facing is the problem occurred in 3.0.7 and patched from the next version.
I will check and let you know again if v3.0.10 still has the same issue.
